name = "ModiaBase"
uuid = "ec7bf1ca-419d-4510-bbab-199861c55244"
authors = ["Hilding Elmqvist <Hilding.Elmqvist@Mogram.net>", "Martin Otter <Martin.Otter@dlr.de>"]
version = "0.9.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataFrames = "1"
DiffRules = "1"
Measurements = "2"
MonteCarloMeasurements = "1"
OrderedCollections = "1"
RecursiveFactorization = "0.2"
StaticArrays = "1"
TimerOutputs = "0.5"
Unitful = "1"
julia = "1.7"
